application: the-blacksmiths-daughter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /static
  static_dir: application/static

- url: .*
  script: run.application.app
